# podman-compose -f etc/docker-compose.yaml up -p erdemo-infra -d 


version: '3.7'

services:

  zookeeper:
    image: quay.io/strimzi/kafka:latest-kafka-2.6.0
    command: [
      "sh", "-c",
      "bin/zookeeper-server-start.sh config/zookeeper.properties"
    ]
    ports:
      - "2181:2181"
    environment:
      LOG_DIR: /tmp/logs
    networks:
      - fhir-bpm-service

  kafka:
    image: quay.io/strimzi/kafka:latest-kafka-2.6.0
    command: [
      "sh", "-c",
      "bin/kafka-server-start.sh config/server.properties --override listeners=PLAINTEXT://127.0.0.1:9092 --override advertised.listeners=PLAINTEXT://127.0.0.1:9092 --override zookeeper.connect=zookeeper:2181"
    ]
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      LOG_DIR: "/tmp/logs"
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://127.0.0.1:9092
      KAFKA_LISTENERS: PLAINTEXT://127.0.0.1:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    networks:
      - fhir-bpm-service

  kafka_connect:
    image: docker.io/debezium/connect:1.5
    depends_on:
      - zookeeper
    ports:
      - "8083:8083"
    environment:
      BOOTSTRAP_SERVERS: 127.0.0.1:9092
      GROUP_ID: 1
      CONFIG_STORAGE_TOPIC: my_connect_configs
      OFFSET_STORAGE_TOPIC: my_connect_offsets
      STATUS_STORAGE_TOPIC: my_connect_statuses
    networks:
      - fhir-bpm-service

  psql_fhir:
    image: registry.redhat.io/rhel8/postgresql-12
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRESQL_USER=fhir
      - POSTGRESQL_PASSWORD=fhir
      - POSTGRESQL_DATABASE=fhir
      - POSTGRESQL_MAX_PREPARED_TRANSACTIONS=10
    volumes:
      # https://github.com/sclorg/postgresql-container/tree/generated/12
      - type: bind
        source: ./hapi-fhir/hapi-psql-wal.conf
        target: /opt/app-root/src/postgresql-cfg/hapi-psql-wal.conf
      - type: bind
        source: ./hapi-fhir/hapi-psql-wal.sh
        target: /opt/app-root/src/postgresql-start/hapi-psql-wal.sh
    networks:
      - fhir-bpm-service

#  psql_rhpam:
#    image: registry.redhat.io/rhel8/postgresql-12
#    restart: always
#    ports:
#      - "6432:6432"
#    environment:
#      - POSTGRESQL_USER=rhpam
#      - POSTGRESQL_PASSWORD=rhpam
#      - POSTGRESQL_DATABASE=rhpam
#      - POSTGRESQL_MAX_PREPARED_TRANSACTIONS=10
#    volumes:
#      - type: bind
#        source: ./rhpam/rhpam-psql.conf
#        target: /opt/app-root/src/postgresql-cfg/rhpam-psql.conf
#      - type: bind
#        source: ./rhpam/ddl-scripts/postgresql/
#        target: /opt/sql
#    networks:
#      - fhir-bpm-service

networks:
  fhir-bpm-service:
    name: fhir-bpm-network
