---


- name: check if {{ application_name }} application is deployed
  oc_obj:
    oc_binary: "{{ openshift_cli }}"
    state: list
    namespace: "{{ namespace }}"
    name: "{{ application_name }}"
    kind: dc
  register: result

- name: "create service account {{ application_name }}"
  oc_serviceaccount:
    oc_binary: "{{ openshift_cli }}"
    state: present
    name: "{{ application_name }}"
    namespace: "{{ namespace }}"

- name: copy application template
  template:
    src: "{{ resources_dir }}/{{ kafdrop_application_template }}"
    dest: "{{ work_dir }}/{{ kafdrop_application_template }}"


- name: deploy {{ application_name }} application
  oc_list:
    oc_binary: "{{ openshift_cli }}"
    state: present
    namespace: "{{ namespace }}"
    files:
      - "{{ work_dir }}/{{ kafdrop_application_template }}"
  when: result.ansible_module_results.stderr is defined and result.ansible_module_results.stderr != ""
