psql_app_name: psql-rhpam
application_name: "sepsisdetection-rhpam"

postgresql_pv_capacity: 5Gi 
postgresql_version: 12-el8
postgresql_is_namespace: openshift
postgresql_service_account: "{{ psql_app_name }}"
psql_user_name: rhpam
psql_user_passwd: rhpam
psql_db_name: rhpam
psql_credentials_secret: "{{ psql_app_name }}"
postgresql_max_prepared_transactions: 100
postgresql_max_connections: 100
postgresql_init_configmap: "{{ psql_app_name }}-init"
postgresql_memory_limit: 512Mi
postgresql_cpu_limit: 500m
postgresql_memory_request: 256Mi
postgresql_cpu_request: 100m
undeploy_psql_bpm: "false"

quartz_clustered: false

service_account: "{{ application_name }}"
application_properties: application.properties
application_configmap: "{{ application_name }}"
application_configmap_key: "{{ application_properties }}"
binary_imagestream_template: binary-imagestream.yml 
service_image: quay.io/redhat_naps_da/sepsisdetection-rhpam
service_image_tag: 0.0.1
application_template: sepsisdetection-rhpam.yml
fhir_bpm_service_java_max_mem_ratio: 60
fhir_bpm_service_java_initial_mem_ratio: 0
fhir_bpm_service_gc_max_metaspace_size: 500

# Location on image file system where sepsisdetection-rhpam.xml  (which defines deployed KIE containers) will reside
kie_server_repo_path: /deployments/config
kie_admin_user: admin
kie_admin_password: user
kieserver_user_password: kieserver

kie_deployment_name: sepsisdetection-kjar
kie_deployment_version: 1.0.0
kie_process_id: 'highmediummitigation'
fhir_server_url: "http://{{ fhir_server_application_name }}:8080"
