---

- name: Deploy all vaccination scheduling artifacts
  hosts: localhost
  connection: local
  gather_facts: false
  run_once: true

  tasks:

    - set_fact:
        namespace: "{{ project_name }}"
        resources_dir: "{{ resources_base_dir }}/amq-streams"
        work_dir_name: "amq-streams-operator"
    - include_role:
        name: ../roles/amq_streams_operator
      when: >
        ACTION is not defined or
        ACTION is none or
        ACTION|trim() == "" or
        ACTION|trim() == "install"
    - include_role:
        name: ../roles/amq_streams_operator
        tasks_from: uninstall
      when: >
        ACTION is defined and
        ACTION|trim() == "uninstall"
