---

- name: Deploy all sepsisdetection artifacts
  hosts: localhost
  connection: local
  gather_facts: false
  run_once: true
  vars_files:
    - group_vars/all.yml
    - group_vars/tools.yml
    - group_vars/kafka_cluster.yml
    - group_vars/hapi_fhirserver.yml
    - group_vars/sepsisdetection_rhpam.yml

  tasks:
  - include: tasks/amq-streams.yml
  - include: tasks/hapi-fhirserver.yml
  - include: tasks/sepsisdetection-rhpam.yml
  - include: tasks/sepsisdetection-ui.yml
